@startuml 

package App{
    package model {
        class User{
            -name
            -email
        }
    }
    note bottom : php artisan make::fillament-resource UserResource --genegrate
    package migration{
        class Create_User{
            -id 
            -name 
        }
    }
    note bottom : php artisan make::fillament-resource UserResource --genegrate
    package fillament-resource{
        class UserResource{
            +test
        }
    }
    note bottom : php artisan make::fillament-resource UserResource --genegrate
}

@enduml 