@startuml
start

:Registrasi Anggota;
:Anggota melakukan registrasi;
:Notifikasi diterima oleh pustakawan;
if (Registrasi disetujui?) then (Ya)
  :Anggota menerima notifikasi penerimaan;
  :Anggota dapat meminjam buku;
else (Tidak)
  :Anggota menerima notifikasi penolakan;
endif

:Melihat Daftar Buku;
:Anggota memilih buku yang tersedia;
:Permintaan peminjaman dikirim ke pustakawan;
if (Buku tersedia?) then (Ya)
  :Peminjaman disetujui;
  :Jadwal pengembalian dikirim ke anggota;
else (Tidak)
  :Permintaan peminjaman dihentikan;
endif

:Pengembalian Buku;
:Pustakawan mencatat status peminjaman;

stop
@enduml
